name: recreate-contributions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -r requirements-test.txt
      - name: Lint with pycodestyle
        run: |
          pycodestyle . --max-line-length=100 --count --show-source --statistics
      - name: Lint with flake8
        run: |
          flake8 . --max-line-length=100 --count --show-source --statistics
      - name: Lint with black
        run: |
          black .
      - name: Test with pytest
        run: |
          pytest --cov=. --cov-branch --cov-report=xml
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0