---
name: Test

on: [push, pull_request]  # yamllint disable-line rule:truthy

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-test.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-test.txt ];
             then pip install -r requirements-test.txt;
          fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Verify all pre-commit hooks
        uses: pre-commit/action@v3.0.1
      - name: Lint with pylint
        run: |
          pylint *.py tests
      - name: Test with pytest
        run: |
          pytest --cov=.
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          name: Python ${{ matrix.python-version }}
